version: "3"

services:
  telegram-bot:
    container_name: doctorinna-telegram-bot
    build: .

    environment:
      DOCTORINNA_BOT_TOKEN: ${DOCTORINNA_BOT_TOKEN}
      DOCTORINNA_BOT_ADMIN: ${DOCTORINNA_BOT_ADMIN}
      DOCTORINNA_API_URL: ${DOCTORINNA_API_URL}

    depends_on:
      - redis-server

  redis-server:
    container_name: doctorinna-redis-server
    image: redis

    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data:
