version: "3"

services:
  telegram-bot:
    container_name: doctorinna-telegram-bot
    build: .

    environment:
      DOCTORINNA_BOT_TOKEN: ${DOCTORINNA_BOT_TOKEN}
      DOCTORINNA_BOT_ADMIN: ${DOCTORINNA_BOT_ADMIN}
      DOCTORINNA_API_URL: ${DOCTORINNA_API_URL}
      DOCTORINNA_REDIS_IP: doctorinna-redis-server

    depends_on:
      - redis-server

  redis-server:
    container_name: doctorinna-redis-server
    image: redis

    ports:
    - 6379:6379

    volumes:
      - redis-data:/data

volumes:
  redis-data:
