name: Build
 
on:
  push:
    branches: [ main, dev ]
    
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9   
        
      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Start Docker containers
        env:
          DOCTORINNA_BOT_TOKEN: ${{ secrets.DOCTORINNA_BOT_TOKEN }}
          DOCTORINNA_BOT_ADMIN: ${{ secrets.DOCTORINNA_BOT_ADMIN }}
          DOCTORINNA_API_URL: ${{ secrets.DOCTORINNA_API_URL }}
        run: docker-compose up -d
      
      - name: Check running containers
        run: docker ps
        
      - name: Check Docker container logs
        run: |
         docker logs doctorinna-telegram-bot
         docker logs doctorinna-redis-server
